directories:
  output: release
  buildResources: build
appId: com.leadingedge.lesoft
productName: LE-SOFT
icon: build/icon.ico
npmRebuild: false
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
extraResources:
  - from: node_modules/sqlite3
    to: node_modules/sqlite3
    filter:
      - '**/*'
  - from: Logo
    to: Logo
    filter:
      - '**/*.png'
afterPack: ./afterPack.cjs
win:
  target: nsis
  icon: build/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: always
  createStartMenuShortcut: true
  shortcutName: LE-SOFT
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
mac:
  target: zip
publish:
  provider: github
  owner: sabbir-404
  repo: Leading-Edge-ECO-System
electronVersion: 29.4.6
